# ---------------------------------------------------------------
#
# Boni Lab
#
# GENERIC model configuration parameters. These parameters are
# used to configure the model for a specific country. The values
# contained in this file are used across country configurations.
#
# PfPR data for calibration comes from the Malaria Atlas Project
# projections for 2017.
# ===============================================================
# ---------------------------------------------------------------
# Items controlling execution of the model
# ---------------------------------------------------------------
# The number of model days between updates to the user
days_between_notifications: 30
# The number to use as the default seed value, comment out or set
# to zero (0) to use random seed.
initial_seed_number: 0
# Connection string for the PostgreSQL database
connection_string: "host=masimdb.vmhost.psu.edu dbname=burkinafaso user=sim password=sim connect_timeout=60"
# Record the genomic data
record_genome_db: false
# Report to GUI and console every 30 days
report_frequency: 30
# ---------------------------------------------------------------
# Dates
# ---------------------------------------------------------------
# Starting date is calibration year minus 11 years of burn-in
starting_date: 2007/1/1               # <-- INPUT VALUE
# 2018 is the target calibration year
start_of_comparison_period: 2018/1/1  # <-- INPUT VALUE
# Ending date is 2023 so we have some extra data to check
ending_date: 2023/12/31               # <-- INPUT VALUE
# Date to start collecting data, 1 year before start of comparison
start_collect_data_day: 1826          # <-- INPUT OR CONFIG VALUE
# ---------------------------------------------------------------
# Items controlling the behavior of the model that are standard
# configuration values across all configurations and all countries
# ---------------------------------------------------------------
# Number of days to keep track total number of parasites in population
number_of_tracking_days: 11
# Transmission parameter based upon MMC data, adjusts the odds that
# an individual will be infected when challenged by sporozoites
transmission_parameter: 0.55
# Age classes used for reporting age-specific mortality calculations
number_of_age_classes: 15
age_structure: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 20, 60, 100]
# Age structure used when initializing the model at T-0
initial_age_structure: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 25, 35, 45, 55, 65, 100]
# Scaling of the population in the model
artificial_rescaling_of_population_size: 1.0
# Crude Birth Rate: 41.2 based upon INSD 2018 data
birth_rate: 0.0412
# Malaria adjusted, all-causes death rate for Burkina Faso
death_rate_by_age_class: [0.0382, 0.03019, 0.02027, 0.01525, 0.01248, 0.00359, 0.00361, 0.00365, 0.00379, 0.00379, 0.00386, 0.00504, 0.0055, 0.0174, 0.0174]
# probability of death for patients who are not treated or patients who experience a treatment failure (due to drug resistance, or otherwise)
# when received treatment, this rate drop by factor of 10 in code
mortality_when_treatment_fail_by_age_class: [0.040, 0.020, 0.020, 0.020, 0.020, 0.004, 0.004, 0.004, 0.004, 0.004, 0.004, 0.001, 0.001, 0.001, 0.001]
# Standard values used in other models
parasite_density_level:
  log_parasite_density_cured:          -4.699    # corresponds to 100 total parasites (0.00002 per μl)
  log_parasite_density_from_liver:     -2.000    # corresponds to 50,000 total parasites (0.01 per μl)
  log_parasite_density_asymptomatic:    3        # corresponds to 1000 parasites per microliter of blood
  log_parasite_density_clinical:        4.301    # corresponds to 20,000 parasites per microliter of blood (total 10^11)
  log_parasite_density_clinical_from:   3.301    # corresponds to 2000 parasites per microliter of blood (total 10^10)
  log_parasite_density_clinical_to:     5.301    # corresponds to 200,000 parasites per microliter of blood (total 10^12)
  log_parasite_density_detectable:      1.000    # corresponds to 10 parasites per microliter of blood
  log_parasite_density_detectable_pfpr: 1.699    # corresponds to 100 parasites per microliter of blood
  log_parasite_density_pyrogenic:       3.398    # corresponds to 2500 parasites per microliter of blood

immune_system_information:
  #rate at which antimalarial immune function increases when a host is parasitaemic
  b1: 0.00125
  #rate at which antimalarial immune function decreases when a host is parasitaemic
  b2: 0.0025
  # durations of infection of naive and fully-immune hosts. 
  # these parameters are used to calculate max and min killing rate by immune system
  duration_for_naive: 300
  duration_for_fully_immune: 60
  # initial conditions for the immune function of the population at time zero
  mean_initial_condition: 0.1
  sd_initial_condition: 0.1
  # (per year) age-dependent faster acquisition of immunity from age 1 to age 10
  immune_inflation_rate: 0.01
  # Max probability of experiencing symptoms as a result of a new infection
  # the actual probability will depend on the host's immunity
  max_clinical_probability: 0.99
  # slope of sigmoidal prob-v-immunity function (parameter z in supplement of 2015 LGH paper) 
  immune_effect_on_progression_to_clinical: 4.5
  # age at which immune function is mature
  age_mature_immunity: 10
  # parameter kappa in supplement of 2015 LGH paper
  factor_effect_age_mature_immunity: 1
  # Adjust the infliction point in the curve
  midpoint: 0.15

# Settings that determine how long an individual stays in a given location
circulation_info:
  max_relative_moving_value: 35
  number_of_moving_levels: 100
  moving_level_distribution:
    distribution: Gamma
    Exponential:
      scale: 0.17
    Gamma:
      mean: 5
      sd: 10
  # Percentage of the population selected for movement outside of their cell each timestep
  circulation_percent: 0.00336
  length_of_stay:
    mean: 5
    sd: 10

# Definition for initial parasite
initial_parasite_info:
  - location_id: -1
    parasite_info:
      # TNY--C1x / 
      # T - CQ resistance (everywhere)
      # NY-- - N (diversity at 86 locus), Y (184 locus)
      # C - Artemisinin (ART) sensitive
      # 1 - PPQ sensitive
      - parasite_type_id: 64
        prevalence: 0.05
      # TYY--C1x
      - parasite_type_id: 72
        prevalence: 0.05

# This number use to determine whether a therapy is "useful" or not and it is used to calculate 
# the useful therapeutic duration of a therapy
tf_rate: 0.1
# Days from end of liver-stage infection to appearance of symptoms
days_to_clinical_under_five: 4
days_to_clinical_over_five: 6
# Days that parasites develop mature gametocyte after exiting liver stage
days_mature_gametocyte_under_five: 4
days_mature_gametocyte_over_five: 6
# Probability of patient compliance
p_compliance: 1
# Minimum dosing days if patient compliance is < 1 - EFFECTIVELY DISABLED 
min_dosing_days: 1
# ---------------------------------------------------------------
# Relative biting rates for individuals
# Uncomment "distribution: Exponential" to use an exponentially 
# distributed biting rate
# ---------------------------------------------------------------
relative_bitting_info:
  max_relative_biting_value: 35
  number_of_biting_levels: 100
  biting_level_distribution:
    #  distribution: Exponential
    distribution: Gamma
    Exponential:
      scale: 0.17
    Gamma:
      mean: 5
      sd: 10

gametocyte_level_under_artemisinin_action: 1.0
gametocyte_level_full: 1.0
# these values are based on Ross 2006 - these parameters determine the probability a mosquito
# becomes infected based on the host's asexual parasitaemia level
relative_infectivity:
  sigma: 3.91
  ro: 0.00031
  # on average 1 mosquito take 3 microliters of blood per bloodeal
  blood_meal_volume: 3

# probability to relapse after no treatment, or a treatment failure due to drug resistance
p_relapse: 0.01
# number of days before a relapse can occur
relapse_duration: 30
# relapse rate - used to increase the parasite density after a treatment failure (at the drug clearance day)
# multiply by sqrt(20) per day
relapseRate: 4.4721
# minimum update frequency for a host's attributes (esp. parasite density) is every 7 days, or
# more frequently if other events are occurring at this time
update_frequency: 7
# if an infected and asymptomatic host is bitten and infected by a new 
# parasite clone, this setting allows the new infection to cause symptoms
allow_new_coinfection_to_cause_symtoms: true
# free recombination among the drug resistance loci
using_free_recombination: true
# the current treatment failure rate as observed in the population is not really
# today's treatment failure rate, as these data are never assembled that quickly in
# real life; rather, it is the average treatment failure rate observed over the 
# past 60 days
tf_window_size: 60
# Mosquitoes always finish their blood meal
fraction_mosquitoes_interrupted_feeding: 0.0
# Follow-up point at which it is determined if treatment failed or not
tf_testing_day: 28 
# TODO - What's this do?
inflation_factor: 0.01
# ---------------------------------------------------------------